# Generated by Django 4.2.3 on 2023-07-18 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='owner_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=10)),
                ('no_of_rooms', models.IntegerField()),
                ('room_price', models.IntegerField()),
                ('single', models.BooleanField(default=False)),
                ('electric_bill', models.IntegerField()),
                ('bathroom', models.CharField(choices=[('attached', 'attached'), ('common', 'common')], max_length=100)),
                ('no_of_bathrooms', models.IntegerField()),
                ('shared_room_pictures', models.FileField(upload_to='')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.owner_details')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
