# Generated by Django 4.2.3 on 2023-07-18 20:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_room_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
