# Generated by Django 4.2.3 on 2023-07-19 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_room_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created_on']},
        ),
    ]
