# Generated by Django 4.2.3 on 2023-07-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_alter_room_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='shared_room_pictures',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
