# Generated by Django 4.2.3 on 2023-07-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_alter_room_shared_room_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='shared_room_pictures',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
