# Generated by Django 4.2.3 on 2023-07-19 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_alter_room_shared_room_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='shared_room_pictures',
        ),
    ]
