# Generated by Django 4.2.3 on 2023-07-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_remove_room_shared_room_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='no_of_rooms',
        ),
        migrations.RemoveField(
            model_name='room',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_price',
        ),
        migrations.RemoveField(
            model_name='room',
            name='single',
        ),
        migrations.AddField(
            model_name='room',
            name='address',
            field=models.TextField(default='Ksudiramnager', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='land_mark',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='locality',
            field=models.CharField(default='Ksudiramnager', max_length=70),
        ),
        migrations.AddField(
            model_name='room',
            name='no_of_shared_room',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='no_of_single_rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='pincode',
            field=models.CharField(default='721657', max_length=6),
        ),
        migrations.AddField(
            model_name='room',
            name='price_of_double_room',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='price_of_single_room',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='total_no_rooms',
            field=models.IntegerField(default=0),
        ),
    ]
