# Generated by Django 4.2.3 on 2023-07-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_rename_shared_room_images_room_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_images',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
