# Generated by Django 4.2.3 on 2023-07-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0012_alter_room_images_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_images',
            name='images',
            field=models.FileField(upload_to=''),
        ),
    ]
