# Generated by Django 4.2.3 on 2023-07-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0013_alter_room_images_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='bathroom',
            field=models.CharField(choices=[('attached', 'attached'), ('common', 'common')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='electric_bill',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='no_of_bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room_images',
            name='images',
            field=models.ImageField(upload_to=''),
        ),
    ]
