# Generated by Django 4.2.3 on 2023-07-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0014_alter_room_bathroom_alter_room_electric_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='building_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
