# Generated by Django 4.2.3 on 2023-08-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0015_room_building_no_alter_room_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_images',
            name='images',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
