# Generated by Django 4.2.3 on 2023-07-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='model_form_shared',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=10)),
                ('no_shared_rooms', models.IntegerField()),
                ('shared_room_price', models.IntegerField()),
                ('electric_bill', models.IntegerField()),
                ('bathroom', models.CharField(choices=[(1, 'attached'), (2, 'common')], max_length=100)),
                ('shared_room_pictures', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='model_form_single',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=10)),
                ('no_single_rooms', models.IntegerField()),
                ('single_room_price', models.IntegerField()),
                ('electric_bill', models.IntegerField()),
                ('bathroom', models.CharField(choices=[(1, 'attached'), (2, 'common')], max_length=100)),
                ('single_room_pictures', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='owner_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('total_rooms', models.IntegerField()),
            ],
        ),
    ]
